### ISSUE TITLE
Discussion channel? IRC, google groups, slack

### ISSUE THREAD

**Issue by zbyte64** [haadcode/orbit-db#108]
I have allot of interest in this project and it would be nice to ask for help or clarification in a chat room setting (instead of polluting github issues). Is there an IRC room I can join to talk to other users and developers?

I have been working on an electron boilerplate with orbit-db and could use some help with orbit-db related questions: https://github.com/zbyte64/electron-react-boilerplate

**Comment by haadcode** [comment]
@zbyte64 great to have you working on this! Best place to ask questions is either here, or on IRC (Freenode, #ipfs). 

Feel free to post your questions here, too, as it'll give others (who are not on IRC) the chance to participate.

**Comment by RichardLitt** [comment]
This could be clearer in the docs. I think we made this clear with the last PR?

**Comment by haadcode** [comment]
@RichardLitt we didn't (for orbit-db). It says currently "Issues, comments, feedback, feature requests and PRs highly welcome!". Wanna PR it? Promise I'll merge it fast :)

**Comment by haadcode** [comment]
Added a mention re. contact info and places to raise questions. Closing.
