### ISSUE TITLE
Make orbit-server (redis) dependency optional

### ISSUE THREAD

**Issue by elsehow** [haadcode/orbit-db#3]
Great work on this package. I'm wondering about the redis dependency, though - theoretically, this could work e.g. with leveldb, correct? And, in that case, we would not need to run an orbit-server instance?

**Comment by haadcode** [comment]
orbit-db in itself doesn't depend on redis. orbit-server does, however. What it's used for is pubsub communication, ie. you send a hash to the server and the server makes sure to send that to everyone who's listening on the topic. in orbit-db this happens via the PubSub class, which in turn communicates with orbit-server via sockets (socket.io).

While it is more or less a hard dependency atm, we're in process of writing an IPFS pubsub that will replace Redis in orbit-server. And eventually, we'll be able to get rid of orbit-server altogether.

I'm not sure how leveldb would replace that mechanism. Can you elaborate what you had in mind?

**Comment by elsehow** [comment]
>  we're in process of writing an IPFS pubsub that will replace Redis in orbit-server

fantastic! do you have any sources where I can learn more about this project?

> I'm not sure how leveldb would replace that mechanism. Can you elaborate what you had in mind?

since we can make a `ReadStream` from a leveldb instance, we could create a subscription mechanism e.g. by filtering the stream with `through`/`through2`

**Comment by haadcode** [comment]
> we're in process of writing an IPFS pubsub that will replace Redis in orbit-server
> fantastic! do you have any sources where I can learn more about this project?

There's a PR in go-ipfs for the early implementation: https://github.com/ipfs/go-ipfs/pull/2599. 

> I'm not sure how leveldb would replace that mechanism. Can you elaborate what you had in mind?
> since we can make a ReadStream from a leveldb instance, we could create a subscription mechanism e.g. by filtering the stream with through/through2

Perhaps there's a misunderstanding as to what Redis does in orbit-db. orbit-server is only a wrapper for Redis' PubSub mechanism, ie. to propagate messages to other peers. leveldb, afaik, doesn't have an implicit messaging system between the leveldb instances to achieve the same, but you have to manually hook it into something that does that and also manually handle the replication of messages across the instances. 

That being said, you could put a leveldb ON TOP of orbit-db and create your own message queue/broker system, or listen for database change/update events. Is that what you want to achieve with leveldb?

**Comment by haadcode** [comment]
We're finally making progress with IPFS pubsub and as such, orbit-db will stop using Redis as the message propagation system as soon as possible.

Work towards that is happening here: https://github.com/haadcode/orbit-db/tree/feat/ipfs-pubsub

**Comment by haadcode** [comment]
This has finally happened! \o/ :)

Version 0.12.0 uses IPFS pubsub to propagate messages to the network. That is: no more servers anywhere!

Closing.

**Comment by edsilv** [comment]
Amazing!
