### ISSUE TITLE
 map/reduce and design docs

### ISSUE THREAD

**Issue by theD1360** [haadcode/orbit-db#35]
I've been through the documentation several times and have been unable to find any references on how to query data from the DB using map/reduce functions. 

PouchDB example:
```
// create a design doc
var ddoc = {
  _id: '_design/index',
  views: {
    index: {
      map: function mapFun(doc) {
        if (doc.title) {
          emit(doc.title);
        }
      }.toString()
    }
  }
}

// save the design doc
db.put(ddoc).catch(function (err) {
  if (err.name !== 'conflict') {
    throw err;
  }
  // ignore if doc already exists
}).then(function () {
  // find docs where title === 'Lisa Says'
  return db.query('index', {
    key: 'Lisa Says',
    include_docs: true
  });
}).then(function (result) {
  // handle result
}).catch(function (err) {
  console.log(err);
});
```

Is there any way to do this in orbit-db?

**Comment by haadcode** [comment]
Hi @theD1360, thanks for the question! The documentation is currently being re-written, so it can be a little hard to find the information you need.

Right now what you want to do is not possible. However, it would be trivial to implement such functionality and I've been wanting to do that at some point.

If I understand your example correctly, you want to index your documents by a specific key, `doc.title`, and find documents by that key. Correct?

In `db.query` you specify the search key `key: 'Lisa Says'`, is that key an *exact* match or *contains* match? Ie. Does the query return a document with title 'Lisa Says Something'?

Do often need to specify the custom key (ie. the mapping function)? Would you want to be able to specify eg. `if(doc.date) emit(doc.data)`?

**Comment by theD1360** [comment]
Hi @haadcode,

Correct. Thank you for the solution but it seems that with the current method all the records need to be pulled then filtered which can be pretty heavy on the browser. If there is a way to store the map/reduce in the document itself it may be a bit less memory intensive. I understand that there is issue open for allowing pouchDB compatibility, this feature may be a critical step towards interoperability.

**Comment by haadcode** [comment]
@theD1360 unless you have gigabytes of docs/entries in your db, modern browser should be able to handle that easily. If you're worried about the performance, however, you could use a library with lazy evaluation, such as lodash or lazy.js which will only process the entries needed in order to achieve the results. Hope that takes you further!

PouchDB integration/interop is not currently on the todo list, would you like to help with that?

**Comment by haadcode** [comment]
@theD1360 Another way would be to use [orbit-db-kvstore](https://github.com/haadcode/orbit-db-kvstore) (also part of orbit-db) and use the `doc.title` as the key. However, this would only work out-of-the-box if your query `key: 'Lisa says'` is an *exact* match and not *contains* match. 

If you need *contains* match, you could, technically, get the keys from the store, find your matches and then get the matching docs separately, thus reducing the mem / performance hit:
```javascript
const db = orbit.kvstore("your db name")
const docs = Object.keys(db._index._index)
  .filter((e) => e === 'Lisa says') // or e.indexOf('Lisa says') > -1 
  .map((e) => db.get(e))
```

**Comment by theD1360** [comment]
@haadcode I will try and set some time aside to really drill down into orbit-db but I don't really have any spare time to donate towards any projects at this moment. I'll try your solution soon though. I have a couple concepts I've been waiting to try out with it. Thanks.

**Comment by haadcode** [comment]
@theD1360 work will be done re. what was discussed above, see here: https://github.com/haadcode/orbit-db/issues/56. If you have any input, we'd be more than happy to hear your thoughts and input!

**Comment by haadcode** [comment]
Hey everyone, this got just merged to orbit-db and we now have a DocumentStore that should similar to what was discussed here. See https://github.com/haadcode/orbit-db/blob/master/API.md#docstorename-options.

Thank you @shamb0t for implementing this.

**Comment by haadcode** [comment]
Closing the issue as this is done. Please do re-open it if you feel there's more work to be done here.
