### ISSUE TITLE
Update READMEs for all orbit-db modules

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit-db#64]
Update the README file in the following repositories:
- [ ] https://github.com/haadcode/ipfs-log
- [ ] https://github.com/haadcode/orbit-db-feedstore
- [ ] https://github.com/haadcode/orbit-db-counterstore
- [ ] https://github.com/haadcode/orbit-db-eventstore
- [ ] https://github.com/haadcode/orbit-db-kvstore
- [ ] https://github.com/haadcode/orbit-db-store

**Comment by RichardLitt** [comment]
Update them with what, exactly?
